name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_publish:
    name: Test and Fuzz
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

    # Need to switch over to nightly at this point to get all the fuzzing
    # capabilities used by `cargo fuzz`.

    - name: Set up Rust nightly for fuzzing
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true

    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz

    - name: Run cargo fuzz
      uses: actions-rs/cargo@v1
      with:
        command: fuzz
        args: run to_vector_validation -- -max_total_time=60
